// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXaCd-ex9Zq4PSzzP2fUhfsh3Nz3EU85I',
    appId: '1:601832219575:web:sadhana_app',
    messagingSenderId: '601832219575',
    projectId: 'sadhana-app-c1836',
    authDomain: 'sadhana-app-c1836.firebaseapp.com',
    storageBucket: 'sadhana-app-c1836.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXaCd-ex9Zq4PSzzP2fUhfsh3Nz3EU85I',
    appId: '1:601832219575:android:3309da71021257da55be32',
    messagingSenderId: '601832219575',
    projectId: 'sadhana-app-c1836',
    storageBucket: 'sadhana-app-c1836.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQpQ6ecA87RUUOIVeSaD413AjaVAQmy0',
    appId: '1:601832219575:ios:7b16879f153078ea55be32',
    messagingSenderId: '601832219575',
    projectId: 'sadhana-app-c1836',
    storageBucket: 'sadhana-app-c1836.firebasestorage.app',
    iosBundleId: 'com.example.sadhanaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJQpQ6ecA87RUUOIVeSaD413AjaVAQmy0',
    appId: '1:601832219575:ios:7b16879f153078ea55be32',
    messagingSenderId: '601832219575',
    projectId: 'sadhana-app-c1836',
    storageBucket: 'sadhana-app-c1836.firebasestorage.app',
    iosBundleId: 'com.example.sadhanaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXaCd-ex9Zq4PSzzP2fUhfsh3Nz3EU85I',
    appId: '1:601832219575:web:sadhana_app',
    messagingSenderId: '601832219575',
    projectId: 'sadhana-app-c1836',
    authDomain: 'sadhana-app-c1836.firebaseapp.com',
    storageBucket: 'sadhana-app-c1836.firebasestorage.app',
  );
}
